### ISSUE TITLE
Question - Raw javascript

### ISSUE THREAD

**Issue by kumavis** [tildeio/oasis.js#76]
Is it possible to provide raw javascript as a string to be sandboxed, instead of a url?

**Comment by lukemelia** [comment]
My understanding is that it would be possible to do this via a data URI, but that there is not robust cross-browser support for this approach. @Cyril-sf or @hjdivad could provide more color.

**Comment by kumavis** [comment]
the `PingPongService` testing fixture https://github.com/tildeio/oasis.js/blob/master/test/fixtures/to_environment.js converted to a data URI via http://software.hixie.ch/utilities/cgi/data/data appears as below

```
data:text/javascript;charset=utf-8,oasis.connect%28%27pingpong%27%2C%20function%28port%29%20%7B%0D%0A%20%20port.on%28%27ping%27%2C%20function%28data%29%20%7B%0D%0A%20%20%20%20port.send%28%27pong%27%2C%20data%29%3B%0D%0A%20%20%7D%29%3B%0D%0A%7D%29%3B%0D%0A
```

I used this to construct the following test:

``` javascript
test("environment can communicate with the sandbox through a port with a shorthand", function() {
    expect(1);

    oasis.register({
      url: 'data:text/javascript;charset=utf-8,oasis.connect%28%27pingpong%27%2C%20function%28port%29%20%7B%0D%0A%20%20port.on%28%27ping%27%2C%20function%28data%29%20%7B%0D%0A%20%20%20%20port.send%28%27pong%27%2C%20data%29%3B%0D%0A%20%20%7D%29%3B%0D%0A%7D%29%3B%0D%0A',
      capabilities: ['pingpong']
    });

    stop();

    var PingPongService = Oasis.Service.extend({
      events: {
        pong: function(data) {
          start();
          equal(data, "PONG", "Got pong from the child");
        }
      },

      initialize: function(port) {
        port.send('ping', "PONG");
      }
    });

    var sandbox = oasis.createSandbox({
      url: 'data:text/javascript;charset=utf-8,oasis.connect%28%27pingpong%27%2C%20function%28port%29%20%7B%0D%0A%20%20port.on%28%27ping%27%2C%20function%28data%29%20%7B%0D%0A%20%20%20%20port.send%28%27pong%27%2C%20data%29%3B%0D%0A%20%20%7D%29%3B%0D%0A%7D%29%3B%0D%0A',
      services: {
        pingpong: PingPongService
      }
    });

    sandbox.start();
  });
```

Running the test I'm getting the following failure message:

`Failed to create a worker: script at '[data uri here]' cannot be accessed from origin 'http://localhost:8000'.`

```
Died on test #1     at http://localhost:8000/test.js:5605:7
    at commonTests (http://localhost:8000/test.js:4682:9)
    at http://localhost:8000/test.js:5479:5
    at requireModule (http://localhost:8000/test.js:33:28)
    at http://localhost:8000/?module=webworker%3A%20Ports:67:9: Failed to create a worker: script at 'data:text/javascript;charset=utf-8,oasis.connect%28%27pingpong%27%2C%20function%28port%29%20%7B%0D%0A%20%20port.on%28%27ping%27%2C%20function%28data%29%20%7B%0D%0A%20%20%20%20port.send%28%27pong%27%2C%20data%29%3B%0D%0A%20%20%7D%29%3B%0D%0A%7D%29%3B%0D%0A' cannot be accessed from origin 'http://localhost:8000'.
Source:     
Error: Failed to create a worker: script at 'data:text/javascript;charset=utf-8,oasis.connect%28%27pingpong%27%2C%20function%28port%29%20%7B%0D%0A%20%20port.on%28%27ping%27%2C%20function%28data%29%20%7B%0D%0A%20%20%20%20port.send%28%27pong%27%2C%20data%29%3B%0D%0A%20%20%7D%29%3B%0D%0A%7D%29%3B%0D%0A' cannot be accessed from origin 'http://localhost:8000'.
    at Object.extend.initializeSandbox (http://localhost:8000/test.js:3898:22)
    at Object.OasisSandbox (http://localhost:8000/test.js:3183:20)
    at Object.Oasis.createSandbox (http://localhost:8000/test.js:2075:16)
    at createSandbox (http://localhost:8000/test.js:4585:34)
    at Object.createWebworkerSandbox [as createSandbox] (http://localhost:8000/test.js:4597:21)
    at Object.<anonymous> (http://localhost:8000/test.js:5628:29)
    at Object.Test.run (http://localhost:8000/vendor/qunit.js:203:18)
    at http://localhost:8000/vendor/qunit.js:369:10
    at process (http://localhost:8000/vendor/qunit.js:1475:24)
    at http://localhost:8000/vendor/qunit.js:487:5
```

**Comment by kumavis** [comment]
An attempt using blobs

``` javascript
test("environment can communicate with the sandbox through a port with a shorthand", function() {
    expect(1);

    // blob generation for webworkers taken from http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string
    // URL.createObjectURL
    var URL = window.URL || window.webkitURL;
    var src = 'oasis.connect("pingpong",function(e){e.on("ping",function(t){e.send("pong",t)})})';
    var blob;
    try {
        blob = new Blob([src], {type: 'application/javascript'});
    } catch (e) { // Backwards-compatibility
        window.BlobBuilder = window.BlobBuilder || window.WebKitBlobBuilder || window.MozBlobBuilder;
        blob = new BlobBuilder();
        blob.append(src);
        blob = blob.getBlob();
    }
    var targetUrl = URL.createObjectURL(blob)

    oasis.register({
      url: targetUrl,
      capabilities: ['pingpong']
    });

    stop();

    var PingPongService = Oasis.Service.extend({
      events: {
        pong: function(data) {
          start();
          equal(data, "PONG", "Got pong from the child");
        }
      },

      initialize: function(port) {
        port.send('ping', "PONG");
      }
    });

    var sandbox = oasis.createSandbox({
      url: targetUrl,
      services: {
        pingpong: PingPongService
      }
    });

    sandbox.start();
  });
```

results in a timeout and a ReferenceError

```
Uncaught ReferenceError: oasis is not defined
Source:     
blob:http%3A//localhost%3A8000/8048fa5b-ce47-49d1-9c83-9598bc1ecb35:1
Test timed out - webworker: Ports environment can communicate with the sandbox through a port with a shorthand
Source:     
    at http://localhost:8000/vendor/qunit.js:506:11
test started: Fri Dec 27 2013 10:05:11 GMT-1000 (HST)
Source:     
    at http://localhost:8000/vendor/qunit.js:507:15
test started: 1388174711100
Source:     
    at http://localhost:8000/vendor/qunit.js:508:15
timer started: 1388174711101
Source:     
    at http://localhost:8000/vendor/qunit.js:509:15
test duration:30005
Source:     
    at http://localhost:8000/vendor/qunit.js:510:15
config timeout: 30000
Source:     
    at http://localhost:8000/vendor/qunit.js:511:15
Expected 1 assertions, but 7 were run
Source:     
    at http://localhost:8000/test.js:5605:7
    at commonTests (http://localhost:8000/test.js:4682:9)
    at http://localhost:8000/test.js:5479:5
    at requireModule (http://localhost:8000/test.js:33:28)
    at http://localhost:8000/?module=webworker%3A%20Ports:67:9
```

**Comment by lukemelia** [comment]
oasis itself would need to be loaded in the iframe

**Comment by kumavis** [comment]
@lukemelia does this not happen automatically? the `fixtures/to_environment.js` file does not explicitly load oasis into the iframe.

**Comment by hjdivad** [comment]
@kumavis Sandboxed Data-URI sourced iframes do not work in any version of internet explorer.  This is the only reason Oasis does not currently take this approach as it's more elegant and easier to debug.  If you look through the commit history you will find an earlier version of Oasis (pre IE support) that took this approach.

If you want IE support, you would need to generate the source in a build step.  If you don't care about IE support, it should be straightforward to create a `DataURIIframeAdapter` and a `DataURIWebWorkerAdapter`, but we're unlikely to put those in Oasis proper.

Can you tell us more about your use case?

**Comment by kumavis** [comment]
I have a multiplayer game to teach coding. It involves (among other things) players writing AI code for non-player characters in the game. This code gets run by the game host and I was interested in using Oasis for sandboxing this code. The code will be produced / change during run time.

**Comment by hjdivad** [comment]
@kumavis if you need to support IE I would recommend creating a `base.html` that basically had an eval capability.

**Comment by kumavis** [comment]
Ah, thats a good solution, thank you.
